version: "3.4"

services:
  node:
    container_name: node
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MONGO_URI:
  mongo:
    container_name: mongo
    image: mongo:4
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
