version: "3.4"

services:
  node_app:
    container_name: node_app
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      MONGO_URI:
      JWT_SECRET:
      REDIS_HOST:
      REDIS_PORT:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - "27017:27017"
    volumes:
      - ./.docker/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:

  redis_app:
    container_name: redis_app
    image: redis:5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - ./.docker/redis/data:/data
