version: "3.4"

services:
  node:
    ports:
      - "4000:4000"
    command: npm run dev
    volumes:
      - ./api:/usr/app
  mongo-express:
    image: mongo-express:0.49
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: "mongo"
