version: "3.4"

services:
  node_app:
    container_name: node_app
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      JWT_SECRET:
      MONGO_URI:
  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
